### ISSUE TITLE
MessageFormat is not defined

### ISSUE THREAD

**Issue by DmitryEfimenko** [planet-training/meteor-angular-translate#2]
According to the [docs](https://angular-translate.github.io/docs/#/guide/14_pluralization) package `angular-translate-interpolation-messageformat` should have dependency on `messageformat.js`. However I don't think it gets loaded. Once package is installed and `$translateProvider.useMessageFormatInterpolation();` is placed in the code, I'm getting error:

```
ReferenceError: MessageFormat is not defined
```

is it expected that I should manually include `messageformat.js`?

Any help is appreciated!

**Comment by dohomi** [comment]
Hi @DmitryEfimenko 
as `Meteor 1.3` published a while ago we stopped using our atmosphere package and moved to the 'npm' package and imported `angular-translate` directly.
`Meteor npm install angular-translate --save`

Then you have the most recent version of the translate package and its dependencies. Hope this helps.

**Comment by DmitryEfimenko** [comment]
sounds great! Thanks for quick reply!
