### ISSUE TITLE
Problem to use static-files

### ISSUE THREAD

**Issue by erperejildo** [planet-training/meteor-angular-translate#4]
After run this:
`meteor add planettraining:angular-translate-loader-static-files`
I get this error: 
Uncaught TypeError: _angular2.default.module(...).component is not a function

Any solution?

**Comment by mxab** [comment]
_angular2 as the new angular?

**Comment by erperejildo** [comment]
I'm using angular-meteor with Angular 1.X. I don't know why I get that error.
I don't even import the plugin, just installing it

**Comment by mxab** [comment]
hmm .component is a function that is introduced with angular 1.5, but actually I would recommend you to use angular-translate via npm directly, this package was just a wrapper before npm package support

**Comment by erperejildo** [comment]
I'm using angular-translate with npm and it's working perfectly but I'd like to use this library for loading reasons.
This one is also available in npm but I'm facing an issue and that's because I'm trying with the Atmosphere's one:
https://github.com/angular-translate/angular-translate/issues/1649#issuecomment-273264076

**Comment by mxab** [comment]
hmm does the network show that the translation gets loaded? in your npm case?

**Comment by erperejildo** [comment]
Checked on Network and yes, the jsons are loaded. I've got these json into the public folder. I've read that another one had a error related with this

**Comment by erperejildo** [comment]
I can't push any test to Punkler or something like that so I made this collage  :)
![sin-titulo-2](https://cloud.githubusercontent.com/assets/5629919/22224394/669beec0-e1b6-11e6-9519-2e672aecda47.jpg)
As you can see I have no errors and json file is loaded well (but just one, I don't know if this is ok)

Is the content of the json file ok?

**Comment by mxab** [comment]
if I read your network correctly it looks like the `en-GB.json` results in a html file that looks like the index

**Comment by erperejildo** [comment]
yeap, it's a bit weird, isn't it?

**Comment by mxab** [comment]
this means the json resouce is not found in your public folder, are you sure that your json files below your meteor application folder in public/langs?

closing this issue as I don't think it is related to this package

**Comment by erperejildo** [comment]
As you can see on the screenshot, the json is located in public/folder. If I change its name I get the new name in Network, so the plugin finds the json.

angular-translate with a var (default and simplest method) works like a charm. The problem comes when I try to use this way to load several jsons.

**Comment by mxab** [comment]
so if you open
http://localhost:3000/public/lang/en-GB.json
http://localhost:3000/public/lang/es-ES.json

in the browser you both times see valid data?

**Comment by erperejildo** [comment]
If I go to those links the app redirects me to the main page (with no errors) but the json loads into Network tab (with same weird content).

**Comment by mxab** [comment]
sorry remove the public in the url path, files that are under the public folder get server from /

`http://localhost:3000/lang/es-ES.json`

**Comment by erperejildo** [comment]
Same than before anyway

**Comment by mxab** [comment]
forgot the s in langs

http://localhost:3000/langs/es-ES.json

**Comment by erperejildo** [comment]
Haven't realized either...
Yes, I get the json:
```
{
  "test": "Esto es una prueba"
}
```
Same for the other one

**Comment by mxab** [comment]
i guess then it should also work if you fix the prefix now to `langs/`

**Comment by erperejildo** [comment]
Oh, you right!

But anyway I tried it first of all with the root of my project and it didn't work. Changing it again to the correct route (public/lang/) doesn't change any behavior (same than screenshot)

**Comment by erperejildo** [comment]
You rocks!

So RESUMING: we need to put our json files into public folder but don't put this folder in `prefix`

Thanks mate!!

**Comment by mxab** [comment]
welcome :)
